CREATE TABLE shows (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    price_paise BIGINT NOT NULL CHECK (price_paise >= 0),
    per_user_limit INTEGER NOT NULL CHECK (per_user_limit > 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE reservations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    show_id BIGINT NOT NULL REFERENCES shows (id),
    user_id BIGINT NOT NULL,
    amount_paise BIGINT NOT NULL CHECK (amount_paise >= 0),
    status TEXT NOT NULL CHECK (status IN ('PENDING', 'CONFIRMED', 'CANCELLED', 'EXPIRED')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_reservations_show_id_id UNIQUE (show_id, id),
    CONSTRAINT uq_reservations_show_id_user UNIQUE (show_id, id, user_id)
);

CREATE INDEX idx_reservations_show_user_created
    ON reservations (show_id, user_id, created_at DESC);

CREATE TABLE seats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    show_id BIGINT NOT NULL REFERENCES shows (id),
    seat_number TEXT NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('AVAILABLE', 'HELD', 'CONFIRMED')),
    reservation_id BIGINT,
    held_until TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_seats_show_seat_number UNIQUE (show_id, seat_number),
    CONSTRAINT uq_seats_reservation_id_id UNIQUE (reservation_id, id),
    CONSTRAINT fk_seats_reservation_show
        FOREIGN KEY (show_id, reservation_id) REFERENCES reservations (show_id, id),
    CONSTRAINT ck_seats_reservation_state CHECK (
        (status = 'AVAILABLE' AND reservation_id IS NULL AND held_until IS NULL)
        OR (status = 'HELD' AND reservation_id IS NOT NULL AND held_until IS NOT NULL)
        OR (status = 'CONFIRMED' AND reservation_id IS NOT NULL AND held_until IS NULL)
    )
);

CREATE INDEX idx_seats_show_status_seat_number
    ON seats (show_id, status, seat_number);

CREATE INDEX idx_seats_reservation_id
    ON seats (reservation_id)
    WHERE reservation_id IS NOT NULL;

CREATE TABLE reservation_seats (
    reservation_id BIGINT NOT NULL REFERENCES reservations (id),
    seat_id BIGINT NOT NULL,
    CONSTRAINT pk_reservation_seats PRIMARY KEY (reservation_id, seat_id),
    CONSTRAINT uq_reservation_seats_seat_id UNIQUE (seat_id),
    CONSTRAINT fk_reservation_seats_seat_reservation
        FOREIGN KEY (reservation_id, seat_id) REFERENCES seats (reservation_id, id)
);

CREATE TABLE idempotency_keys (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    show_id BIGINT NOT NULL REFERENCES shows (id),
    idempotency_key TEXT NOT NULL CHECK (idempotency_key <> ''),
    request_hash TEXT NOT NULL CHECK (request_hash <> ''),
    reservation_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_idempotency_user_show_key UNIQUE (user_id, show_id, idempotency_key),
    CONSTRAINT uq_idempotency_reservation UNIQUE (reservation_id),
    CONSTRAINT fk_idempotency_reservation_owner
        FOREIGN KEY (show_id, reservation_id, user_id)
        REFERENCES reservations (show_id, id, user_id)
);
